// ============================================================================
// JurisFlow — Dados de demonstração (mock) ricamente estruturados
// Representam um escritório de advocacia médio em operação
// ============================================================================

import type {
  UserProfile,
  Cliente,
  Processo,
  Documento,
  Tarefa,
  InboxJuridicoItem,
  Automacao,
  Notificacao,
  EventoAgenda,
} from "./types";

export const currentUser: UserProfile = {
  id: "u-001",
  nome: "Dra. Marina Vidal",
  email: "marina.vidal@vidaladvogados.com.br",
  oab: "SP 287.419",
  perfil: "socio",
  escritorio: "Vidal & Associados Advocacia",
  permissoes: ["*"],
  preferencias: {
    notificacoesDataJud: true,
    resumoIaAutomatico: true,
    tema: "system",
  },
};

export const escritorioStats = {
  totalProcessos: 87,
  processosAtivos: 64,
  clientesAtivos: 52,
  tarefasPendentes: 23,
  prazosProximos7Dias: 9,
  faturamentoMes: 184750,
  recebimentoMes: 142300,
  produtividade: 78,
  taxaSucesso: 71,
};

export const clientes: Cliente[] = [
  {
    id: "c-001",
    nome: "Construtora Horizonte Ltda",
    tipo: "PJ",
    cpfCnpj: "12.345.678/0001-90",
    email: "juridico@horizonteconstrutora.com.br",
    telefone: "(11) 3322-1100",
    endereco: {
      logradouro: "Av. das Nações, 1500 — Sala 1204",
      cidade: "São Paulo",
      uf: "SP",
      cep: "04538-132",
    },
    historicoNotas:
      "Cliente PJ desde 2019. Volume médio de 18 processos trabalhistas ativos. Pagamento pontual. Prefere relatórios quinzenais por e-mail.",
    processosVinculados: ["p-001", "p-004"],
    dataCadastro: "2019-03-12",
    status: "Ativo",
  },
  {
    id: "c-002",
    nome: "Ricardo Almeida Souza",
    tipo: "PF",
    cpfCnpj: "***.456.789-**",
    email: "ricardo.souza@gmail.com",
    telefone: "(21) 99876-5432",
    endereco: {
      logradouro: "Rua das Laranjeiras, 222 — Apto 801",
      cidade: "Rio de Janeiro",
      uf: "RJ",
      cep: "22240-006",
    },
    historicoNotas:
      "Cliente PF. Ação trabalhista contra ex-empregador. Sensível a atualizações — manter comunicação frequente.",
    processosVinculados: ["p-002"],
    dataCadastro: "2024-08-21",
    status: "Ativo",
  },
  {
    id: "c-003",
    nome: "TechNova Soluções S/A",
    tipo: "PJ",
    cpfCnpj: "98.765.432/0001-10",
    email: "legal@technova.com.br",
    telefone: "(11) 4002-8922",
    endereco: {
      logradouro: "Rua Funchal, 418 — 14º andar",
      cidade: "São Paulo",
      uf: "SP",
      cep: "04551-060",
    },
    historicoNotas:
      "Cliente PJ do setor de tecnologia. Contratos complexos, propriedade intelectual. Alta exposição contratual.",
    processosVinculados: ["p-003"],
    dataCadastro: "2022-11-05",
    status: "Ativo",
  },
  {
    id: "c-004",
    nome: "Helena Ferreira Martins",
    tipo: "PF",
    cpfCnpj: "***.789.123-**",
    email: "helena.martins@outlook.com",
    telefone: "(31) 98123-4567",
    endereco: {
      logradouro: "Av. Afonso Pena, 800 — Apto 302",
      cidade: "Belo Horizonte",
      uf: "MG",
      cep: "30130-003",
    },
    historicoNotas:
      "Ação de família — divórcio litigioso com partilha de bens. Dois filhos menores envolvidos.",
    processosVinculados: ["p-005"],
    dataCadastro: "2024-12-02",
    status: "Ativo",
  },
  {
    id: "c-005",
    nome: "Logística Expressa S/A",
    tipo: "PJ",
    cpfCnpj: "55.444.333/0001-22",
    email: "contato@logexpressa.com.br",
    telefone: "(41) 3222-7788",
    endereco: {
      logradouro: "Rod. BR-116, km 98 — Galpão 7",
      cidade: "Curitiba",
      uf: "PR",
      cep: "81730-000",
    },
    historicoNotas: "Cliente prospect. Negociação de contrato de assessoria mensal em andamento.",
    processosVinculados: [],
    dataCadastro: "2025-01-15",
    status: "Potencial",
  },
];

export const processos: Processo[] = [
  {
    id: "p-001",
    numeroCnj: "0012345-67.2023.5.02.0001",
    tribunal: "TRT-2",
    comarca: "São Paulo/SP",
    classeProcessual: "Reclamação Trabalhista",
    assunto: "Verbas rescisórias e horas extras",
    area: "Trabalhista",
    risco: "Alto",
    partes: {
      poloAtivo: "João Carlos Bezerra — ex-empregado",
      poloPassivo: "Construtora Horizonte Ltda",
    },
    advogadoResponsavelId: "u-001",
    advogadoResponsavelNome: "Dra. Marina Vidal",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    status: "Ativo",
    tags: ["alto-valor", "estratégico", "risco-alto"],
    documentosIds: ["d-001", "d-002"],
    datasImportantes: {
      distribuicao: "2023-03-15",
      proximaAudiencia: "2026-08-05",
      prazoFatal: "2026-08-01",
    },
    valorCausa: 285000,
    ultimaSincronizacaoDataJud: "2026-07-25T08:14:00Z",
    resumoIa:
      "Reclamação trabalhista de ex-empregado do setor de obras solicitando verbas rescisórias, horas extras e adicional de insalubridade. Ré contestou documentos. Perícia contábil designada. Risco de condenação estimado em 60-75% do valor pedido, principalmente pelo histórico de cartões de ponto inconsistentes.",
    probabilidadeSucesso: 35,
    movimentacoes: [
      {
        id: "m-001",
        data: "2026-07-22",
        descricao: "Publicada sentença parcial — acolhimento parcial dos pedidos de horas extras",
        orgao: "1ª Vara do Trabalho — São Paulo/SP",
        fonte: "DataJud",
        relevancia: "Alta",
        alertaIa: "Condenação parcial. Avaliar viabilidade de recurso ordinário no prazo de 8 dias.",
      },
      {
        id: "m-002",
        data: "2026-06-10",
        descricao: "Audiência una realizada — instrução encerrada",
        orgao: "1ª Vara do Trabalho",
        fonte: "DataJud",
        relevancia: "Alta",
      },
      {
        id: "m-003",
        data: "2026-05-03",
        descricao: "Deferida produção de prova testemunhal",
        orgao: "1ª Vara do Trabalho",
        fonte: "Diário Oficial",
        relevancia: "Média",
      },
      {
        id: "m-004",
        data: "2026-04-18",
        descricao: "Designada audiência una",
        orgao: "1ª Vara do Trabalho",
        fonte: "DataJud",
        relevancia: "Média",
      },
      {
        id: "m-005",
        data: "2026-03-22",
        descricao: "Apresentada contestação",
        orgao: "1ª Vara do Trabalho",
        fonte: "Manual",
        relevancia: "Alta",
      },
      {
        id: "m-006",
        data: "2023-03-15",
        descricao: "Distribuição — Reclamação Trabalhista",
        orgao: "1ª Vara do Trabalho — São Paulo/SP",
        fonte: "DataJud",
        relevancia: "Alta",
      },
    ],
  },
  {
    id: "p-002",
    numeroCnj: "0045678-12.2024.5.01.0007",
    tribunal: "TRT-1",
    comarca: "Rio de Janeiro/RJ",
    classeProcessual: "Reclamação Trabalhista",
    assunto: "Reconhecimento de vínculo e verbas",
    area: "Trabalhista",
    risco: "Médio",
    partes: {
      poloAtivo: "Ricardo Almeida Souza",
      poloPassivo: "Transportes Carioca Ltda",
    },
    advogadoResponsavelId: "u-001",
    advogadoResponsavelNome: "Dra. Marina Vidal",
    clienteId: "c-002",
    clienteNome: "Ricardo Almeida Souza",
    status: "Ativo",
    tags: ["cliente-pf", "audiência-próxima"],
    documentosIds: ["d-003"],
    datasImportantes: {
      distribuicao: "2024-09-12",
      proximaAudiencia: "2026-07-30",
      prazoFatal: "2026-07-29",
    },
    valorCausa: 68500,
    ultimaSincronizacaoDataJud: "2026-07-26T03:20:00Z",
    resumoIa:
      "Ação trabalhista do polo ativo. Audiência inicial designada para a próxima semana. Razoável probabilidade de acordo (60%) dado perfil do reclamante e histórico similar.",
    probabilidadeSucesso: 65,
    movimentacoes: [
      {
        id: "m-007",
        data: "2026-07-12",
        descricao: "Designada audiência inicial",
        orgao: "7ª Vara do Trabalho — Rio de Janeiro/RJ",
        fonte: "DataJud",
        relevancia: "Alta",
        alertaIa: "Audiência em 4 dias — preparar proposta de acordo e dossiê completo.",
      },
      {
        id: "m-008",
        data: "2024-09-12",
        descricao: "Distribuição",
        orgao: "7ª Vara do Trabalho",
        fonte: "DataJud",
        relevancia: "Alta",
      },
    ],
  },
  {
    id: "p-003",
    numeroCnj: "1009876-54.2023.8.26.0100",
    tribunal: "TJSP",
    comarca: "São Paulo/SP",
    classeProcessual: "Procedimento Comum Cível",
    assunto: "Quebra de contrato e perdas e danos",
    area: "Empresarial",
    risco: "Alto",
    partes: {
      poloAtivo: "TechNova Soluções S/A",
      poloPassivo: "CloudProvider Brasil Ltda",
    },
    advogadoResponsavelId: "u-001",
    advogadoResponsavelNome: "Dra. Marina Vidal",
    clienteId: "c-003",
    clienteNome: "TechNova Soluções S/A",
    status: "Em Recurso",
    tags: ["alto-valor", "estratégico", "tecnologia"],
    documentosIds: ["d-004"],
    datasImportantes: {
      distribuicao: "2023-07-04",
      prazoFatal: "2026-08-12",
    },
    valorCausa: 1240000,
    ultimaSincronizacaoDataJud: "2026-07-24T16:45:00Z",
    resumoIa:
      "Ação cível de quebra contratual por falha em serviços de nuvem. Sentença de procedência parcial. Apelação em curso. Forte documentação técnica. Probabilidade de melhoria no segundo grau: 45%.",
    probabilidadeSucesso: 55,
    movimentacoes: [
      {
        id: "m-009",
        data: "2026-07-20",
        descricao: "Intimação para contrarrazões",
        orgao: "TJSP — 4ª Câmara de Direito Empresarial",
        fonte: "Diário Oficial",
        relevancia: "Alta",
        alertaIa: "Prazo fatal em 23 dias. Preparar contrarrazões com ênfase em danos lucros cessantes.",
      },
      {
        id: "m-010",
        data: "2026-06-15",
        descricao: "Apelação interposta pela ré",
        orgao: "TJSP",
        fonte: "DataJud",
        relevancia: "Alta",
      },
      {
        id: "m-011",
        data: "2026-04-30",
        descricao: "Sentença — procedência parcial",
        orgao: "3ª Vara Cível — São Paulo/SP",
        fonte: "DataJud",
        relevancia: "Alta",
      },
    ],
  },
  {
    id: "p-004",
    numeroCnj: "0023456-78.2025.4.03.6100",
    tribunal: "TRF-3",
    comarca: "São Paulo/SP",
    classeProcessual: "Mandado de Segurança",
    assunto: "Exclusão de ICMS na base do PIS/COFINS",
    area: "Tributário",
    risco: "Baixo",
    partes: {
      poloAtivo: "Construtora Horizonte Ltda",
      poloPassivo: "Delegacia da Receita Federal em São Paulo",
    },
    advogadoResponsavelId: "u-001",
    advogadoResponsavelNome: "Dra. Marina Vidal",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    status: "Ativo",
    tags: ["tributário", "tese-repetitiva", "baixo-risco"],
    documentosIds: [],
    datasImportantes: {
      distribuicao: "2025-02-10",
    },
    valorCausa: 380000,
    ultimaSincronizacaoDataJud: "2026-07-25T11:00:00Z",
    resumoIa:
      "Mandado de segurança com base em tese firmada pelo STF (Tema 69). Alta probabilidade de êxito (~85%). Aguardando informações da autoridade coatora.",
    probabilidadeSucesso: 85,
    movimentacoes: [
      {
        id: "m-012",
        data: "2026-07-18",
        descricao: "Conversão em diligência para informações da autoridade coatora",
        orgao: "TRF-3 — 8ª Turma",
        fonte: "DataJud",
        relevancia: "Média",
      },
      {
        id: "m-013",
        data: "2025-02-10",
        descricao: "Distribuição",
        orgao: "TRF-3",
        fonte: "DataJud",
        relevancia: "Alta",
      },
    ],
  },
  {
    id: "p-005",
    numeroCnj: "0078901-23.2024.8.26.0010",
    tribunal: "TJSP",
    comarca: "São Paulo/SP",
    classeProcessual: "Divórcio Litigioso",
    assunto: "Dissolução de casamento, partilha e guarda",
    area: "Família",
    risco: "Médio",
    partes: {
      poloAtivo: "Helena Ferreira Martins",
      poloPassivo: "Pedro Henrique Martins",
    },
    advogadoResponsavelId: "u-001",
    advogadoResponsavelNome: "Dra. Marina Vidal",
    clienteId: "c-004",
    clienteNome: "Helena Ferreira Martins",
    status: "Ativo",
    tags: ["família", "guarda-menores", "sensível"],
    documentosIds: [],
    datasImportantes: {
      distribuicao: "2024-12-15",
      proximaAudiencia: "2026-08-18",
    },
    valorCausa: 0,
    ultimaSincronizacaoDataJud: "2026-07-23T14:30:00Z",
    resumoIa:
      "Divórcio litigioso com partilha de bens e guarda de dois menores. Equipe técnica (psicólogo) designada. Audiência de conciliação agendada para agosto.",
    probabilidadeSucesso: 70,
    movimentacoes: [
      {
        id: "m-014",
        data: "2026-07-05",
        descricao: "Designada audiência de conciliação",
        orgao: "2ª Vara de Família — São Paulo/SP",
        fonte: "DataJud",
        relevancia: "Alta",
      },
      {
        id: "m-015",
        data: "2026-05-20",
        descricao: "Deferida produção de prova pericial psicológica",
        orgao: "2ª Vara de Família",
        fonte: "Diário Oficial",
        relevancia: "Média",
      },
    ],
  },
];

export const documentos: Documento[] = [
  {
    id: "d-001",
    tipo: "Contrato",
    nome: "Contrato de Trabalho — João Carlos Bezerra.pdf",
    arquivoUrl: "/docs/contrato-bezerra.pdf",
    tamanho: "2.4 MB",
    dataUpload: "2023-03-18",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteId: "c-001",
    resumoIa:
      "Contrato de trabalho CLT firmado em 12/03/2018. Jornada 44h/semana. Salário inicial R$ 3.500. Cláusula de hora extra mediante acordo. Sem cláusula de não-concorrência. Vigência indeterminada, rescindida em 02/2023.",
    entidadesExtraidas: {
      datas: ["12/03/2018", "02/2023"],
      valores: ["R$ 3.500,00", "R$ 4.200,00 (atual)"],
      clausulasCriticas: [
        "Jornada 44h/semana — potencial descumprimento pelas anotações de ponto",
        "Acordo de hora extra — possível reflexo em DSR e 13º",
      ],
      partesCitadas: ["João Carlos Bezerra", "Construtora Horizonte Ltda"],
    },
    statusIa: "analisado",
  },
  {
    id: "d-002",
    tipo: "Contestação",
    nome: "Contestação — Processo 0012345-67.2023.docx",
    arquivoUrl: "/docs/contestacao-001.pdf",
    tamanho: "880 KB",
    dataUpload: "2026-03-22",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteId: "c-001",
    resumoIa:
      "Contestação apresentada em 22/03/2026. Alegação de pagamento integral, prescrição quinquenal, inexistência de horas extras e regularidade dos cartões de ponto eletrônico. Produção de prova testemunhal requerida.",
    entidadesExtraidas: {
      datas: ["22/03/2026"],
      valores: [],
      clausulasCriticas: [
        "Tese de prescrição quinquenal — verificar marco inicial",
        "Cartões de ponto eletrônico — risco de inversão do ônus se invalidados",
      ],
      partesCitadas: ["João Carlos Bezerra", "Construtora Horizonte Ltda"],
    },
    statusIa: "analisado",
  },
  {
    id: "d-003",
    tipo: "Petição Inicial",
    nome: "Petição Inicial — Ricardo Souza.pdf",
    arquivoUrl: "/docs/inicial-ricardo.pdf",
    tamanho: "1.1 MB",
    dataUpload: "2024-09-12",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    clienteId: "c-002",
    resumoIa:
      "Petição inicial postulando reconhecimento de vínculo empregatício (período 2019-2024), verbas rescisórias, horas extras e multa do art. 477 §6º CLT. Valor da causa R$ 68.500.",
    entidadesExtraidas: {
      datas: ["2019-2024"],
      valores: ["R$ 68.500,00"],
      clausulasCriticas: [
        "Pedido de multa do art. 477 §6º — verificar regularidade do pagamento rescisório",
      ],
      partesCitadas: ["Ricardo Almeida Souza", "Transportes Carioca Ltda"],
    },
    statusIa: "analisado",
  },
  {
    id: "d-004",
    tipo: "Sentença",
    nome: "Sentença — TechNova x CloudProvider.pdf",
    arquivoUrl: "/docs/sentenca-technova.pdf",
    tamanho: "1.8 MB",
    dataUpload: "2026-05-02",
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    clienteId: "c-003",
    resumoIa:
      "Sentença de procedência parcial. Acolhimento de quebra contratual, mas não reconhecimento de lucros cessantes. Indenização fixada em R$ 420 mil, abaixo do pedido de R$ 1.24 mi. Honorários de 10% sobre o proveito econômico.",
    entidadesExtraidas: {
      datas: ["30/04/2026"],
      valores: ["R$ 420.000,00", "R$ 1.240.000,00 (pedido)", "Honorários 10%"],
      clausulasCriticas: [
        "Não acolhimento de lucros cessantes — ponto central da apelação",
        "Honorários fixados no piso da tabela — possível majoração",
      ],
      partesCitadas: ["TechNova Soluções S/A", "CloudProvider Brasil Ltda"],
    },
    statusIa: "analisado",
  },
  {
    id: "d-005",
    tipo: "Procuração",
    nome: "Procuração — Helena Martins.pdf",
    arquivoUrl: "/docs/procuracao-helena.pdf",
    tamanho: "210 KB",
    dataUpload: "2024-12-02",
    processoId: "p-005",
    processoNumeroCnj: "0078901-23.2024.8.26.0010",
    clienteId: "c-004",
    resumoIa: "Procuração ad judiciais com poderes gerais foro e especiais para divórcio e partilha.",
    statusIa: "analisado",
  },
  {
    id: "d-006",
    tipo: "Contrato",
    nome: "Contrato de Prestação de Serviços Jurídicos — Modelo 2026.docx",
    arquivoUrl: "/docs/modelo-contrato-2026.docx",
    tamanho: "340 KB",
    dataUpload: "2026-01-10",
    resumoIa: "Modelo padrão de honorários com cláusulas de honorários sucumbenciais,EXIT e foro.",
    statusIa: "pendente",
  },
];

export const tarefas: Tarefa[] = [
  {
    id: "t-001",
    descricao: "Preparar contrarrazões de apelação — TechNova x CloudProvider",
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-08-12",
    prioridade: "Urgente",
    status: "Pendente",
    categoria: "Prazo Processual",
  },
  {
    id: "t-002",
    descricao: "Dossiê de audiência — Ricardo Souza (audiência 30/07)",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-07-29",
    prioridade: "Urgente",
    status: "Em Andamento",
    categoria: "Audiência",
  },
  {
    id: "t-003",
    descricao: "Avaliar recurso ordinário — sentença parcial Bezerra",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-08-01",
    prioridade: "Alta",
    status: "Pendente",
    categoria: "Prazo Processual",
  },
  {
    id: "t-004",
    descricao: "Reunião com Helena Martins — atualização guarda",
    processoId: "p-005",
    processoNumeroCnj: "0078901-23.2024.8.26.0010",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-07-28",
    prioridade: "Alta",
    status: "Pendente",
    categoria: "Reunião",
  },
  {
    id: "t-005",
    descricao: "Anexar cartões de ponto eletrônicos ao processo Bezerra",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-07-27",
    prioridade: "Média",
    status: "Em Andamento",
    categoria: "Diligência",
  },
  {
    id: "t-006",
    descricao: "Emitir fatura mensal — Construtora Horizonte",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-08-05",
    prioridade: "Média",
    status: "Pendente",
    categoria: "Interno",
  },
  {
    id: "t-007",
    descricao: "Solicitar certidão de objeto e pé — TRF-3",
    processoId: "p-004",
    processoNumeroCnj: "0023456-78.2025.4.03.6100",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-08-10",
    prioridade: "Baixa",
    status: "Pendente",
    categoria: "Diligência",
  },
  {
    id: "t-008",
    descricao: "Revisar modelo de contrato de honorários 2026",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-08-15",
    prioridade: "Baixa",
    status: "Pendente",
    categoria: "Interno",
  },
  {
    id: "t-009",
    descricao: "Preparar proposta de acordo — Ricardo Souza",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    responsavelId: "u-001",
    responsavelNome: "Dra. Marina Vidal",
    dataLimite: "2026-07-28",
    prioridade: "Alta",
    status: "Concluído",
    categoria: "Interno",
  },
];

export const inboxItens: InboxJuridicoItem[] = [
  {
    id: "i-001",
    tipo: "Movimentação DataJud",
    titulo: "Publicada sentença parcial — Bezerra x Construtora Horizonte",
    descricao: "1ª Vara do Trabalho de São Paulo publicou sentença com acolhimento parcial dos pedidos. Condenação estimada em R$ 165 mil.",
    dataHora: "2026-07-22T11:30:00Z",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteNome: "Construtora Horizonte Ltda",
    classificacaoIa: "Ação Necessária",
    sugestaoAcaoIa: "Avaliar recurso ordinário no prazo de 8 dias úteis. Condenação abaixo do esperado — providenciar análise de viabilidade econômica do recurso.",
    prazoSugeridoDias: 8,
    lido: false,
    arquivado: false,
  },
  {
    id: "i-002",
    tipo: "Movimentação DataJud",
    titulo: "Audiência inicial designada — Ricardo Souza",
    descricao: "Audiência inicial marcada para 30/07 às 14h na 7ª Vara do Trabalho do Rio de Janeiro.",
    dataHora: "2026-07-12T15:00:00Z",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    clienteNome: "Ricardo Almeida Souza",
    classificacaoIa: "Ação Necessária",
    sugestaoAcaoIa: "Preparar dossiê completo, proposta de acordo (faixa 35-50% do pedido) e orientar cliente sobre procedimento.",
    prazoSugeridoDias: 4,
    lido: false,
    arquivado: false,
  },
  {
    id: "i-003",
    tipo: "Publicação Diário Oficial",
    titulo: "Intimação para contrarrazões — TechNova x CloudProvider",
    descricao: "TJSP — 4ª Câmara de Direito Empresarial intima para apresentação de contrarrazões em 15 dias.",
    dataHora: "2026-07-20T08:00:00Z",
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    clienteNome: "TechNova Soluções S/A",
    classificacaoIa: "Ação Necessária",
    sugestaoAcaoIa: "Prazo fatal de 15 dias. Foco em lucros cessantes e majoração de honorários. Iniciar imediatamente.",
    prazoSugeridoDias: 15,
    lido: false,
    arquivado: false,
  },
  {
    id: "i-004",
    tipo: "E-mail Cliente",
    titulo: "Helena Martins solicita reagendamento de reunião",
    descricao: "Cliente pede para remarcar reunião de quarta para sexta-feira devido a compromisso médico da filha.",
    dataHora: "2026-07-25T18:42:00Z",
    processoId: "p-005",
    clienteNome: "Helena Ferreira Martins",
    classificacaoIa: "Importante",
    sugestaoAcaoIa: "Confirmar novo horário e ajustar agenda. Manter comunicação empática — cliente em momento delicado.",
    lido: false,
    arquivado: false,
  },
  {
    id: "i-005",
    tipo: "Documento Recebido",
    titulo: "Cartões de ponto eletrônicos — Construtora Horizonte",
    descricao: "Cliente enviou os cartões de ponto do período 2018-2023 solicitados em diligência.",
    dataHora: "2026-07-26T09:15:00Z",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteNome: "Construtora Horizonte Ltda",
    classificacaoIa: "Importante",
    sugestaoAcaoIa: "Anexar ao processo e solicitar análise pericial comparativa com anotações manuais.",
    lido: true,
    arquivado: false,
  },
  {
    id: "i-006",
    tipo: "Publicação Diário Oficial",
    titulo: "TRF-3 converte MS em diligência — Construtora Horizonte",
    descricao: "TRF-3 solicita informações da autoridade coatora (Receita Federal) em 30 dias.",
    dataHora: "2026-07-18T12:00:00Z",
    processoId: "p-004",
    processoNumeroCnj: "0023456-78.2025.4.03.6100",
    clienteNome: "Construtora Horizonte Ltda",
    classificacaoIa: "Pode Esperar",
    sugestaoAcaoIa: "Acompanhar resposta da Receita. Alta probabilidade de êxito pela tese firmada pelo STF (Tema 69).",
    lido: true,
    arquivado: false,
  },
];

export const automacoes: Automacao[] = [
  {
    id: "a-001",
    nome: "Alerta de Prazo Fatal — 7 dias",
    descricao: "Cria tarefa urgente quando um processo tem prazo fatal a menos de 7 dias.",
    gatilho: "Prazo fatal detectado via DataJud",
    acao: "Criar tarefa + notificar advogado responsável + destacar no dashboard",
    ativa: true,
    execucoesUltimos30Dias: 14,
    ultimaExecucao: "2026-07-22T11:31:00Z",
    tipo: "Prazo",
  },
  {
    id: "a-002",
    nome: "Resumo IA de Movimentações",
    descricao: "Gera resumo automático de cada nova movimentação processual via IA.",
    gatilho: "Nova movimentação no DataJud",
    acao: "Analisar com IA + classificar relevância + sugerir ação + adicionar resumo ao processo",
    ativa: true,
    execucoesUltimos30Dias: 47,
    ultimaExecucao: "2026-07-26T03:20:00Z",
    tipo: "Movimentação",
  },
  {
    id: "a-003",
    nome: "Triagem de Inbox Jurídico",
    descricao: "Classifica automaticamente todos os itens do inbox por prioridade de ação.",
    gatilho: "Nova publicação/e-mail/DataJud",
    acao: "Classificar (Ação Necessária/Importante/Pode Esperar) + sugerir ação + estimar prazo",
    ativa: true,
    execucoesUltimos30Dias: 89,
    ultimaExecucao: "2026-07-26T09:15:00Z",
    tipo: "Movimentação",
  },
  {
    id: "a-004",
    nome: "Relatório Quinzenal — Construtora Horizonte",
    descricao: "Gera relatório consolidado de todos os processos do cliente a cada 15 dias.",
    gatilho: "Agendado: dias 1 e 16 do mês",
    acao: "Compilar processos + movimentações + prazos + faturamento + enviar por e-mail ao cliente",
    ativa: true,
    execucoesUltimos30Dias: 2,
    ultimaExecucao: "2026-07-16T10:00:00Z",
    tipo: "Agendada",
  },
  {
    id: "a-005",
    nome: "Análise IA de Documentos Recebidos",
    descricao: "Extrai entidades e gera resumo de cada documento novo anexado a um processo.",
    gatilho: "Upload de documento",
    acao: "Extrair datas/valores/partes + identificar cláusulas críticas + gerar resumo IA + atualizar entidades",
    ativa: true,
    execucoesUltimos30Dias: 23,
    ultimaExecucao: "2026-07-26T09:16:00Z",
    tipo: "Documento",
  },
  {
    id: "a-006",
    nome: "Lembrete de Audiência — 48h antes",
    descricao: "Envia lembrete ao advogado e ao cliente 48 horas antes de cada audiência.",
    gatilho: "Audiência agendada a menos de 48h",
    acao: "Notificar advogado + e-mail ao cliente com orientações + destacar no dashboard",
    ativa: true,
    execucoesUltimos30Dias: 6,
    ultimaExecucao: "2026-07-24T14:00:00Z",
    tipo: "Agendada",
  },
  {
    id: "a-007",
    nome: "Onboarding de Novo Cliente",
    descricao: "Cria tarefas padrão quando um novo cliente é cadastrado.",
    gatilho: "Novo cliente criado",
    acao: "Criar tarefa: contrato + procuração + cadastro + reunião inicial + documento de governança",
    ativa: false,
    execucoesUltimos30Dias: 0,
    ultimaExecucao: "2026-06-12T15:30:00Z",
    tipo: "Cliente",
  },
];

export const notificacoes: Notificacao[] = [
  {
    id: "n-001",
    titulo: "Sentença publicada — Bezerra x Horizonte",
    descricao: "Condenação parcial. Prazo de recurso em 8 dias.",
    tipo: "warning",
    lida: false,
    dataHora: "2026-07-22T11:31:00Z",
    link: "processos",
  },
  {
    id: "n-002",
    titulo: "Audiência em 3 dias — Ricardo Souza",
    descricao: "30/07 às 14h — 7ª VT Rio de Janeiro",
    tipo: "warning",
    lida: false,
    dataHora: "2026-07-26T08:00:00Z",
    link: "tarefas",
  },
  {
    id: "n-003",
    titulo: "Documento analisado pela IA",
    descricao: "Cartões de ponto eletrônicos — Construtora Horizonte. 3 cláusulas críticas identificadas.",
    tipo: "success",
    lida: false,
    dataHora: "2026-07-26T09:18:00Z",
    link: "documentos",
  },
  {
    id: "n-004",
    titulo: "Sincronização DataJud concluída",
    descricao: "5 processos sincronizados. 2 novas movimentações.",
    tipo: "info",
    lida: true,
    dataHora: "2026-07-26T03:22:00Z",
    link: "processos",
  },
  {
    id: "n-005",
    titulo: "Automação executada — Relatório Quinzenal",
    descricao: "Relatório enviado para juridico@horizonteconstrutora.com.br",
    tipo: "success",
    lida: true,
    dataHora: "2026-07-16T10:01:00Z",
    link: "automacoes",
  },
];

export const eventosAgenda: EventoAgenda[] = [
  {
    id: "e-001",
    titulo: "Audiência Inicial — Ricardo Souza",
    data: "2026-07-30",
    hora: "14:00",
    tipo: "Audiência",
    processoId: "p-002",
    clienteNome: "Ricardo Almeida Souza",
  },
  {
    id: "e-002",
    titulo: "Prazo fatal — Contrarrazões TechNova",
    data: "2026-08-12",
    hora: "23:59",
    tipo: "Prazo",
    processoId: "p-003",
    clienteNome: "TechNova Soluções S/A",
  },
  {
    id: "e-003",
    titulo: "Reunião — Helena Martins",
    data: "2026-07-28",
    hora: "10:00",
    tipo: "Reunião",
    processoId: "p-005",
    clienteNome: "Helena Ferreira Martins",
  },
  {
    id: "e-004",
    titulo: "Audiência Una — Bezerra",
    data: "2026-08-05",
    hora: "09:30",
    tipo: "Audiência",
    processoId: "p-001",
    clienteNome: "Construtora Horizonte Ltda",
  },
  {
    id: "e-005",
    titulo: "Audiência Conciliação — Helena Martins",
    data: "2026-08-18",
    hora: "13:30",
    tipo: "Audiência",
    processoId: "p-005",
    clienteNome: "Helena Ferreira Martins",
  },
];

// Dados para gráficos do dashboard

export const faturamentoMensal = [
  { mes: "Fev", recebido: 92000, faturado: 124000 },
  { mes: "Mar", recebido: 138000, faturado: 162000 },
  { mes: "Abr", recebido: 121000, faturado: 158000 },
  { mes: "Mai", recebido: 145000, faturado: 171000 },
  { mes: "Jun", recebido: 134000, faturado: 165000 },
  { mes: "Jul", recebido: 142300, faturado: 184750 },
];

export const processosPorArea = [
  { area: "Trabalhista", quantidade: 28, fill: "var(--chart-1)" },
  { area: "Cível", quantidade: 19, fill: "var(--chart-2)" },
  { area: "Tributário", quantidade: 14, fill: "var(--chart-3)" },
  { area: "Empresarial", quantidade: 11, fill: "var(--chart-4)" },
  { area: "Família", quantidade: 9, fill: "var(--chart-5)" },
  { area: "Outros", quantidade: 6, fill: "var(--chart-2)" },
];

export const produtividadeSemanal = [
  { dia: "Seg", tarefas: 12, concluidas: 9 },
  { dia: "Ter", tarefas: 14, concluidas: 11 },
  { dia: "Qua", tarefas: 10, concluidas: 8 },
  { dia: "Qui", tarefas: 16, concluidas: 12 },
  { dia: "Sex", tarefas: 11, concluidas: 9 },
  { dia: "Sáb", tarefas: 4, concluidas: 3 },
  { dia: "Dom", tarefas: 1, concluidas: 1 },
];

// ============================================================================
// GESTÃO DE EQUIPE — Membros, papéis e permissões
// ============================================================================

import type {
  LancamentoFinanceiro,
  ContratoHonorarios,
  JurisprudenciaItem,
  TendenciaJurisprudencial,
  InsightProativo,
  ProcessosPorEstado,
  GargaloEscritorio,
  AnalisePreditiva,
  MembroEquipe,
  PapelEquipeConfig,
  Permissao,
} from "./types";

// Configuração dos 4 papéis — usado no formulário e na listagem
export const papeisEquipe: PapelEquipeConfig[] = [
  {
    value: "socio",
    label: "Sócio",
    descricao:
      "Acesso total. Gerencia equipe, contratos, financeiro e configurações do escritório.",
    cor: "text-primary",
    corBg: "bg-primary/10",
    permissoesPadrao: [
      "dashboard:view",
      "processos:view",
      "processos:edit",
      "processos:delete",
      "clientes:view",
      "clientes:edit",
      "tarefas:view",
      "tarefas:edit",
      "documentos:view",
      "documentos:edit",
      "documentos:delete",
      "financeiro:view",
      "financeiro:edit",
      "equipe:view",
      "equipe:edit",
      "configuracoes:view",
      "configuracoes:edit",
      "copiloto:use",
      "jurisprudencia:view",
      "automacoes:edit",
    ],
  },
  {
    value: "advogado",
    label: "Advogado",
    descricao:
      "Acesso a processos, clientes, tarefas, documentos e Copiloto IA. Sem acesso a financeiro e equipe.",
    cor: "text-chart-2",
    corBg: "bg-chart-2/10",
    permissoesPadrao: [
      "dashboard:view",
      "processos:view",
      "processos:edit",
      "clientes:view",
      "clientes:edit",
      "tarefas:view",
      "tarefas:edit",
      "documentos:view",
      "documentos:edit",
      "copiloto:use",
      "jurisprudencia:view",
    ],
  },
  {
    value: "secretaria",
    label: "Secretária",
    descricao:
      "Acesso a agenda, clientes, tarefas administrativas e documentos. Sem acesso a processos judiciais.",
    cor: "text-info",
    corBg: "bg-info/10",
    permissoesPadrao: [
      "dashboard:view",
      "clientes:view",
      "clientes:edit",
      "tarefas:view",
      "tarefas:edit",
      "documentos:view",
      "documentos:edit",
    ],
  },
  {
    value: "estagiario",
    label: "Estagiário",
    descricao:
      "Acesso limitado a processos atribuídos, tarefas designadas e documentos. Sem edição de clientes.",
    cor: "text-warning",
    corBg: "bg-warning/15",
    permissoesPadrao: [
      "dashboard:view",
      "processos:view",
      "tarefas:view",
      "tarefas:edit",
      "documentos:view",
    ],
  },
];

// Catálogo de todas as permissões (para o checklist no formulário)
export const permissoesCatalogo: { value: Permissao; label: string; grupo: string }[] = [
  { value: "dashboard:view", label: "Ver dashboard", grupo: "Geral" },
  { value: "copiloto:use", label: "Usar Copiloto IA", grupo: "Geral" },
  { value: "jurisprudencia:view", label: "Ver jurisprudência", grupo: "Geral" },
  { value: "processos:view", label: "Ver processos", grupo: "Processos" },
  { value: "processos:edit", label: "Editar processos", grupo: "Processos" },
  { value: "processos:delete", label: "Excluir processos", grupo: "Processos" },
  { value: "clientes:view", label: "Ver clientes", grupo: "Clientes" },
  { value: "clientes:edit", label: "Editar clientes", grupo: "Clientes" },
  { value: "tarefas:view", label: "Ver tarefas", grupo: "Tarefas" },
  { value: "tarefas:edit", label: "Editar tarefas", grupo: "Tarefas" },
  { value: "documentos:view", label: "Ver documentos", grupo: "Documentos" },
  { value: "documentos:edit", label: "Editar documentos", grupo: "Documentos" },
  { value: "documentos:delete", label: "Excluir documentos", grupo: "Documentos" },
  { value: "financeiro:view", label: "Ver financeiro", grupo: "Financeiro" },
  { value: "financeiro:edit", label: "Editar financeiro", grupo: "Financeiro" },
  { value: "equipe:view", label: "Ver equipe", grupo: "Equipe" },
  { value: "equipe:edit", label: "Editar equipe", grupo: "Equipe" },
  { value: "configuracoes:view", label: "Ver configurações", grupo: "Configurações" },
  { value: "configuracoes:edit", label: "Editar configurações", grupo: "Configurações" },
  { value: "automacoes:edit", label: "Editar automações", grupo: "Configurações" },
];

export const membrosEquipe: MembroEquipe[] = [
  {
    id: "me-001",
    nome: "Dra. Marina Vidal",
    email: "marina.vidal@vidaladvogados.com.br",
    papel: "socio",
    oab: "SP 287.419",
    telefone: "(11) 99876-5432",
    iniciais: "MV",
    status: "ativo",
    dataEntrada: "2018-03-12",
    processosAtribuidos: 38,
    tarefasPendentes: 8,
    produtividade: 92,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-07-27T08:14:00Z",
    cargaHoraria: "Integral",
    permissoes: papeisEquipe[0].permissoesPadrao as Permissao[],
  },
  {
    id: "me-002",
    nome: "Dr. Rafael Costa",
    email: "rafael.costa@vidaladvogados.com.br",
    papel: "socio",
    oab: "SP 312.587",
    telefone: "(11) 98123-4567",
    iniciais: "RC",
    status: "ferias",
    dataEntrada: "2018-03-12",
    processosAtribuidos: 24,
    tarefasPendentes: 0,
    produtividade: 88,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-07-15T17:30:00Z",
    cargaHoraria: "Integral",
    permissoes: papeisEquipe[0].permissoesPadrao as Permissao[],
  },
  {
    id: "me-003",
    nome: "Dra. Beatriz Lima",
    email: "beatriz.lima@vidaladvogados.com.br",
    papel: "advogado",
    oab: "SP 412.876",
    telefone: "(11) 97777-1234",
    iniciais: "BL",
    status: "ativo",
    dataEntrada: "2022-08-01",
    processosAtribuidos: 19,
    tarefasPendentes: 6,
    produtividade: 84,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-07-27T07:55:00Z",
    supervisor: "Dra. Marina Vidal",
    cargaHoraria: "Integral",
    permissoes: papeisEquipe[1].permissoesPadrao as Permissao[],
  },
  {
    id: "me-004",
    nome: "Dr. Carlos Eduardo Rocha",
    email: "carlos.rocha@vidaladvogados.com.br",
    papel: "advogado",
    oab: "RJ 187.234",
    telefone: "(21) 99888-7766",
    iniciais: "CR",
    status: "ativo",
    dataEntrada: "2023-02-15",
    processosAtribuidos: 12,
    tarefasPendentes: 4,
    produtividade: 78,
    escritorio: "Vidal & Associados — Filial Rio de Janeiro",
    ultimoAcesso: "2026-07-26T19:22:00Z",
    supervisor: "Dr. Rafael Costa",
    cargaHoraria: "Integral",
    permissoes: papeisEquipe[1].permissoesPadrao as Permissao[],
  },
  {
    id: "me-005",
    nome: "Ana Paula Mendes",
    email: "ana.mendes@vidaladvogados.com.br",
    papel: "secretaria",
    telefone: "(11) 3322-1100",
    iniciais: "AM",
    status: "ativo",
    dataEntrada: "2020-06-10",
    processosAtribuidos: 0,
    tarefasPendentes: 11,
    produtividade: 95,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-07-27T08:01:00Z",
    supervisor: "Dra. Marina Vidal",
    cargaHoraria: "Integral",
    permissoes: papeisEquipe[2].permissoesPadrao as Permissao[],
  },
  {
    id: "me-006",
    nome: "Juliana Santos",
    email: "juliana.santos@vidaladvogados.com.br",
    papel: "secretaria",
    telefone: "(21) 3456-7890",
    iniciais: "JS",
    status: "ativo",
    dataEntrada: "2024-01-08",
    processosAtribuidos: 0,
    tarefasPendentes: 7,
    produtividade: 89,
    escritorio: "Vidal & Associados — Filial Rio de Janeiro",
    ultimoAcesso: "2026-07-26T18:45:00Z",
    supervisor: "Dr. Carlos Eduardo Rocha",
    cargaHoraria: "Parcial",
    permissoes: papeisEquipe[2].permissoesPadrao as Permissao[],
  },
  {
    id: "me-007",
    nome: "Pedro Henrique Alves",
    email: "pedro.alves@vidaladvogados.com.br",
    papel: "estagiario",
    telefone: "(11) 96666-5544",
    iniciais: "PA",
    status: "ativo",
    dataEntrada: "2025-01-20",
    processosAtribuidos: 5,
    tarefasPendentes: 9,
    produtividade: 72,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-07-27T07:30:00Z",
    supervisor: "Dra. Beatriz Lima",
    cargaHoraria: "Estágio",
    permissoes: papeisEquipe[3].permissoesPadrao as Permissao[],
  },
  {
    id: "me-008",
    nome: "Mariana Oliveira",
    email: "mariana.oliveira@vidaladvogados.com.br",
    papel: "estagiario",
    telefone: "(11) 95555-3322",
    iniciais: "MO",
    status: "afastado",
    dataEntrada: "2024-07-15",
    processosAtribuidos: 3,
    tarefasPendentes: 0,
    produtividade: 0,
    escritorio: "Vidal & Associados — Sede São Paulo",
    ultimoAcesso: "2026-06-30T16:00:00Z",
    supervisor: "Dra. Beatriz Lima",
    cargaHoraria: "Estágio",
    permissoes: papeisEquipe[3].permissoesPadrao as Permissao[],
  },
];

export const lancamentosFinanceiros: LancamentoFinanceiro[] = [
  {
    id: "lf-001",
    tipo: "Honorário",
    descricao: "Honorários mensais — Construtora Horizonte (Jul/26)",
    valor: 18500,
    dataVencimento: "2026-08-05",
    status: "Pendente",
    categoria: "Honorários Contratuais",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    formaPagamento: "Boleto",
    recorrente: true,
  },
  {
    id: "lf-002",
    tipo: "Honorário",
    descricao: "Sucesso — Acordo Ricardo Souza",
    valor: 13700,
    dataVencimento: "2026-08-15",
    status: "Agendado",
    categoria: "Honorários de Sucesso",
    clienteId: "c-002",
    clienteNome: "Ricardo Almeida Souza",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    formaPagamento: "PIX",
  },
  {
    id: "lf-003",
    tipo: "Receita",
    descricao: "Pagamento recebido — TechNova (Jun/26)",
    valor: 22000,
    dataVencimento: "2026-07-10",
    dataPagamento: "2026-07-08",
    status: "Pago",
    categoria: "Honorários Contratuais",
    clienteId: "c-003",
    clienteNome: "TechNova Soluções S/A",
    formaPagamento: "Transferência",
  },
  {
    id: "lf-004",
    tipo: "Despesa",
    descricao: "Custas processuais — Distribuição TechNova",
    valor: 1240,
    dataVencimento: "2026-07-25",
    dataPagamento: "2026-07-22",
    status: "Pago",
    categoria: "Custas Judiciais",
    clienteId: "c-003",
    clienteNome: "TechNova Soluções S/A",
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    formaPagamento: "Boleto",
  },
  {
    id: "lf-005",
    tipo: "Despesa",
    descricao: "Perícia contábil — Bezerra x Horizonte",
    valor: 4500,
    dataVencimento: "2026-08-20",
    status: "Pendente",
    categoria: "Honorários Periciais",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
  },
  {
    id: "lf-006",
    tipo: "Honorário",
    descricao: "Mensalidade — Helena Martins",
    valor: 3500,
    dataVencimento: "2026-08-10",
    status: "Pendente",
    categoria: "Honorários Contratuais",
    clienteId: "c-004",
    clienteNome: "Helena Ferreira Martins",
    processoId: "p-005",
    processoNumeroCnj: "0078901-23.2024.8.26.0010",
    formaPagamento: "PIX",
    recorrente: true,
  },
  {
    id: "lf-007",
    tipo: "Despesa",
    descricao: "Aluguel do escritório — Jul/26",
    valor: 8500,
    dataVencimento: "2026-07-31",
    status: "Atrasado",
    categoria: "Despesas Operacionais",
  },
  {
    id: "lf-008",
    tipo: "Despesa",
    descricao: "Software jurídico (ProJuris/LEGAL.ONE) — Jul/26",
    valor: 1280,
    dataVencimento: "2026-08-01",
    status: "Pendente",
    categoria: "Software",
    formaPagamento: "Cartão",
    recorrente: true,
  },
  {
    id: "lf-009",
    tipo: "Receita",
    descricao: "Recebido — Exit processo MS Tributário",
    valor: 38000,
    dataVencimento: "2026-07-15",
    dataPagamento: "2026-07-15",
    status: "Pago",
    categoria: "Honorários de Sucesso",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    processoId: "p-004",
    processoNumeroCnj: "0023456-78.2025.4.03.6100",
    formaPagamento: "Transferência",
  },
  {
    id: "lf-010",
    tipo: "Custa",
    descricao: "Diligência — Cartório de Protestos",
    valor: 380,
    dataVencimento: "2026-08-08",
    status: "Pendente",
    categoria: "Custas Extrajudiciais",
    formaPagamento: "Dinheiro",
  },
];

export const contratosHonorarios: ContratoHonorarios[] = [
  {
    id: "ch-001",
    clienteId: "c-001",
    clienteNome: "Construtora Horizonte Ltda",
    tipo: "Mensal",
    valorBase: 18500,
    vigenciaInicio: "2024-01-01",
    status: "Ativo",
    proximoVencimento: "2026-08-05",
    valorProximaParcela: 18500,
  },
  {
    id: "ch-002",
    clienteId: "c-002",
    clienteNome: "Ricardo Almeida Souza",
    tipo: "Sucesso",
    valorBase: 0,
    percentualSucesso: 20,
    vigenciaInicio: "2024-09-12",
    status: "Ativo",
    processoId: "p-002",
    proximoVencimento: "2026-08-15",
    valorProximaParcela: 13700,
  },
  {
    id: "ch-003",
    clienteId: "c-003",
    clienteNome: "TechNova Soluções S/A",
    tipo: "Misto",
    valorBase: 18000,
    percentualSucesso: 15,
    vigenciaInicio: "2023-07-01",
    status: "Ativo",
    processoId: "p-003",
    proximoVencimento: "2026-08-10",
    valorProximaParcela: 18000,
  },
  {
    id: "ch-004",
    clienteId: "c-004",
    clienteNome: "Helena Ferreira Martins",
    tipo: "Fixo",
    valorBase: 3500,
    vigenciaInicio: "2024-12-15",
    vigenciaFim: "2026-12-15",
    status: "Ativo",
    processoId: "p-005",
    proximoVencimento: "2026-08-10",
    valorProximaParcela: 3500,
  },
];

export const fluxoCaixaMensal = [
  { mes: "Fev", receita: 124000, despesa: 78000 },
  { mes: "Mar", receita: 162000, despesa: 84000 },
  { mes: "Abr", receita: 158000, despesa: 81000 },
  { mes: "Mai", receita: 171000, despesa: 89000 },
  { mes: "Jun", receita: 165000, despesa: 91000 },
  { mes: "Jul", receita: 184750, despesa: 96500 },
];

// ============================================================================
// JURISPRUDÊNCIA IA
// ============================================================================

export const jurisprudencias: JurisprudenciaItem[] = [
  {
    id: "j-001",
    tribunal: "TST",
    classe: "Recurso de Revista",
    relator: "Min. Maria Helena Mallmann",
    dataJulgamento: "2026-06-12",
    ementa:
      "RECURSO DE REVISTA. HORAS EXTRAS. CARTÕES DE PONTO ELETRÔNICOS. PRESUNÇÃO RELATIVA. ÔNUS DA PROVA DO EMPREGADOR. Os cartões de ponto eletrônicos gozam de presunção relativa de veracidade, incumbindo ao empregado a prova inicial de que os horários registrados não correspondem à realidade. Comprovada a irregularidade, inverte-se o ônus probatório.",
    tese: "Cartões de ponto eletrônicos têm presunção relativa de veracidade; comprovada irregularidade, inverte-se o ônus probatório",
    area: "Trabalhista",
    favoravel: false,
    processoOrigem: "RR-1000123-67.2023.5.02.0001",
    relevanceScore: 92,
  },
  {
    id: "j-002",
    tribunal: "STF",
    classe: "RE",
    relator: "Min. Dias Toffoli",
    dataJulgamento: "2026-05-08",
    ementa:
      "ICMS NA BASE DE CÁLCULO DO PIS E DA COFINS. TEMA 69. Modulação dos efeitos da decisão. Empresas que não ajuizaram ação até 15/03/2017 têm direito apenas aos 5 anos anteriores ao ajuizamento.",
    tese: "Exclusão do ICMS da base do PIS/COFINS. Sem ação até 15/03/2017: prescrição quinquenal",
    area: "Tributário",
    favoravel: true,
    processoOrigem: "RE 574706",
    relevanceScore: 98,
  },
  {
    id: "j-003",
    tribunal: "STJ",
    classe: "REsp",
    relator: "Min. Nancy Andrighi",
    dataJulgamento: "2026-06-22",
    ementa:
      "RESPONSABILIDADE CIVIL. QUEBRA DE CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE TI. LUCROS CESSANTES. CONFIGURAÇÃO. A quebra de contrato de prestação de serviços essenciais, cuja interrupção inviabiliza a atividade econômica do contratante, autoriza a condenação em lucros cessantes desde que comprovado o nexo causal e a extensão do dano.",
    tese: "Quebra de contrato de TI essencial autoriza lucros cessantes se comprovado nexo causal",
    area: "Empresarial",
    favoravel: true,
    processoOrigem: "REsp 1234567/SP",
    relevanceScore: 89,
  },
  {
    id: "j-004",
    tribunal: "TJSP",
    classe: "Apelação Cível",
    relator: "Des. Pereira Calças",
    dataJulgamento: "2026-04-18",
    ementa:
      "DIVÓRCIO LITIGIOSO. GUARDA DE MENORES. AVALIAÇÃO PSICOSSOCIAL. PRINCÍPIO DO MELHOR INTERESSE. A guarda compartilhada é regra, mesmo em casos litigiosos. A guarda unilateral exige prova robusta de inadequação de um dos genitores.",
    tese: "Guarda compartilhada como regra; unilateral exige prova robusta de inadequação",
    area: "Família",
    favoravel: true,
    processoOrigem: "Apelação 1009876-54.2023.8.26.0100",
    relevanceScore: 85,
  },
  {
    id: "j-005",
    tribunal: "TRT-2",
    classe: "RO",
    relator: "Des. Rosa Maria Zuccaro",
    dataJulgamento: "2026-06-30",
    ementa:
      "RECURSO ORDINÁRIO. VERBAS RESCISÓRIAS. ACORDO EXTRAJUDICIAL. HOMOLOGAÇÃO. QUITAÇÃO AMPLA. O acordo extrajudicial homologado pela Justiça do Trabalho produz coisa julgada apenas quanto aos direitos expressamente nele insertos.",
    tese: "Acordo homologado quita apenas direitos expressamente previstos",
    area: "Trabalhista",
    favoravel: true,
    processoOrigem: "RO 0012345-67.2023.5.02.0001",
    relevanceScore: 78,
  },
];

export const tendenciasJurisprudenciais: TendenciaJurisprudencial[] = [
  {
    area: "Trabalhista",
    tribunal: "TST",
    tendencia: "Favorável",
    percentualFavoravel: 68,
    totalDecisoes: 1247,
    variacaoMes: 4,
    tesePredominante: "Cartões de ponto eletrônico — presunção relativa e inversão do ônus",
  },
  {
    area: "Tributário",
    tribunal: "STF",
    tendencia: "Favorável",
    percentualFavoravel: 87,
    totalDecisoes: 412,
    variacaoMes: 2,
    tesePredominante: "Exclusão do ICMS da base do PIS/COFINS (Tema 69)",
  },
  {
    area: "Empresarial",
    tribunal: "STJ",
    tendencia: "Favorável",
    percentualFavoravel: 71,
    totalDecisoes: 689,
    variacaoMes: 6,
    tesePredominante: "Lucros cessantes em quebra contratual com nexo causal comprovado",
  },
  {
    area: "Família",
    tribunal: "TJSP",
    tendencia: "Favorável",
    percentualFavoravel: 82,
    totalDecisoes: 1893,
    variacaoMes: -2,
    tesePredominante: "Guarda compartilhada como regra, mesmo em casos litigiosos",
  },
  {
    area: "Cível",
    tribunal: "STJ",
    tendencia: "Contrária",
    percentualFavoravel: 38,
    totalDecisoes: 956,
    variacaoMes: -5,
    tesePredominante: "Redução de indenização por danos morais em valores considerados excessivos",
  },
];

// ============================================================================
// COPILOTO PROATIVO — Insights gerados em background
// ============================================================================

export const insightsProativos: InsightProativo[] = [
  {
    id: "ip-001",
    tipo: "prazo_urgente",
    severidade: "critica",
    titulo: "Contrarrazões TechNova — prazo fatal em 16 dias",
    descricao:
      "O processo TechNova x CloudProvider tem prazo fatal para contrarrazões em 16 dias. Considerando a complexidade (lucros cessantes + honorários), recomendo iniciar imediatamente.",
    acaoSugerida: "Iniciar rascunho das contrarrazões com ênfase em lucros cessantes e majoração de honorários. Agendar revisão técnica em 10 dias.",
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    clienteNome: "TechNova Soluções S/A",
    prazoDias: 16,
    impactoFinanceiro: 380000,
  },
  {
    id: "ip-002",
    tipo: "movimentacao_importante",
    severidade: "alta",
    titulo: "Sentença parcial publicada — Bezerra x Horizonte",
    descricao:
      "Condenação abaixo do esperado (R$ 165 mil vs. R$ 285 mil pedido). Análise preliminar indica viabilidade de recurso ordinário com foco em horas extras e adicional de insalubridade.",
    acaoSugerida: "Avaliar recurso ordinário no prazo de 8 dias. Calcular custo-benefício (honorários recursais vs. probabilidade de melhoria ~40%).",
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteNome: "Construtora Horizonte Ltda",
    prazoDias: 8,
    impactoFinanceiro: 120000,
    probabilidadeSucesso: 40,
  },
  {
    id: "ip-003",
    tipo: "cliente_sem_contato",
    severidade: "media",
    titulo: "Helena Martins sem contato há 21 dias",
    descricao:
      "Cliente sensível (caso de família com menores) sem atualização há 3 semanas. Em ações de divórcio litigioso, a comunicação frequente reduz ansiedade e evita queixas.",
    acaoSugerida: "Enviar atualização por e-mail hoje com status do processo, próximos passos e data da audiência (18/08). Considerar ligação de 10min.",
    clienteNome: "Helena Ferreira Martins",
    processoId: "p-005",
    processoNumeroCnj: "0078901-23.2024.8.26.0010",
  },
  {
    id: "ip-004",
    tipo: "documento_faltante",
    severidade: "alta",
    titulo: "Documentos faltantes — Processo TechNova",
    descricao:
      "Faltam anexar: contrato de SLA original, e-mails de notificação de falhas, faturas dos 6 últimos meses. Esses documentos são essenciais para as contrarrazões.",
    acaoSugerida: "Solicitar formalmente à TechNova os documentos em 24h. Criar tarefa para acompanhamento.",
    processoId: "p-003",
    clienteNome: "TechNova Soluções S/A",
  },
  {
    id: "ip-005",
    tipo: "oportunidade_acordo",
    severidade: "media",
    titulo: "Oportunidade de acordo — Ricardo Souza",
    descricao:
      "Audiência inicial em 4 dias. Análise de processos similares no TRT-1 mostra 60% de probabilidade de acordo na faixa de 35-50% do pedido. Cliente provavelmente aceitará proposta razoável.",
    acaoSugerida: "Preparar proposta de acordo em R$ 24-34 mil (35-50% do pedido). Apresentar na audiência inicial como alternativa à instrução.",
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    clienteNome: "Ricardo Almeida Souza",
    prazoDias: 4,
    impactoFinanceiro: 13700,
    probabilidadeSucesso: 60,
  },
  {
    id: "ip-006",
    tipo: "risco_perda",
    severidade: "critica",
    titulo: "Risco de perda de prazo — Aluguel do escritório",
    descricao:
      "Despesa de aluguel (R$ 8.500) venceu em 31/07 e está atrasada. Atrasos recorrentes podem gerar multa de 10% + juros e risco de denúncia do contrato.",
    acaoSugerida: "Efetuar pagamento imediato. Verificar fluxo de caixa — recebimentos do mês (R$ 142,3k) cobrem folha e despesas.",
    impactoFinanceiro: 8500,
  },
  {
    id: "ip-007",
    tipo: "oportunidade_sucesso",
    severidade: "media",
    titulo: "Alta probabilidade de êxito — MS Tributário",
    descricao:
      "Processo de MS (Construtora Horizonte) com 85% de probabilidade de êxito pela tese firmada pelo STF (Tema 69). Considerar cobrança antecipada dos honorários de sucesso.",
    acaoSugerida: "Enviar cobrança antecipada dos honorários de sucesso (R$ 38k) e planejar fluxo de caixa para agosto.",
    processoId: "p-004",
    processoNumeroCnj: "0023456-78.2025.4.03.6100",
    clienteNome: "Construtora Horizonte Ltda",
    impactoFinanceiro: 38000,
    probabilidadeSucesso: 85,
  },
  {
    id: "ip-008",
    tipo: "gargalo_produto",
    severidade: "baixa",
    titulo: "23 tarefas pendentes — gargalo operacional",
    descricao:
      "Número de tarefas pendentes acima da média histórica (16). Distribuição: 9 prazos processuais, 6 diligências, 5 reuniões. Risco de atraso em cascada.",
    acaoSugerida: "Delegar 4 tarefas de diligência para estagiário. Adiar 2 reuniões não-urgentes. Foco em prazos processuais.",
  },
];

// ============================================================================
// MAPA DE PROCESSOS POR ESTADO
// ============================================================================

export const processosPorEstado: ProcessosPorEstado[] = [
  {
    uf: "SP",
    estado: "São Paulo",
    total: 41,
    ativos: 32,
    valorTotal: 4280000,
    coord: { lat: -23.55, lng: -46.63 },
    comarcas: [
      { nome: "São Paulo", total: 28 },
      { nome: "Campinas", total: 8 },
      { nome: "Santos", total: 5 },
    ],
  },
  {
    uf: "RJ",
    estado: "Rio de Janeiro",
    total: 18,
    ativos: 14,
    valorTotal: 1240000,
    coord: { lat: -22.9, lng: -43.17 },
    comarcas: [
      { nome: "Rio de Janeiro", total: 12 },
      { nome: "Niterói", total: 4 },
      { nome: "Petrópolis", total: 2 },
    ],
  },
  {
    uf: "MG",
    estado: "Minas Gerais",
    total: 12,
    ativos: 9,
    valorTotal: 890000,
    coord: { lat: -19.92, lng: -43.94 },
    comarcas: [
      { nome: "Belo Horizonte", total: 8 },
      { nome: "Contagem", total: 4 },
    ],
  },
  {
    uf: "PR",
    estado: "Paraná",
    total: 8,
    ativos: 6,
    valorTotal: 520000,
    coord: { lat: -25.42, lng: -49.27 },
    comarcas: [
      { nome: "Curitiba", total: 6 },
      { nome: "Londrina", total: 2 },
    ],
  },
  {
    uf: "RS",
    estado: "Rio Grande do Sul",
    total: 5,
    ativos: 4,
    valorTotal: 380000,
    coord: { lat: -30.03, lng: -51.23 },
    comarcas: [{ nome: "Porto Alegre", total: 5 }],
  },
  {
    uf: "BA",
    estado: "Bahia",
    total: 3,
    ativos: 2,
    valorTotal: 210000,
    coord: { lat: -12.97, lng: -38.5 },
    comarcas: [{ nome: "Salvador", total: 3 }],
  },
];

// ============================================================================
// MODO ESTRATÉGICO — Gargalos e análise preditiva
// ============================================================================

export const gargalosEscritorio: GargaloEscritorio[] = [
  {
    categoria: "Tempo de resposta a movimentações",
    descricao: "Tempo médio de 4,2 dias entre movimentação e ação do escritório",
    impacto: "Alto",
    metrica: "Dias médios de resposta",
    valorAtual: 4.2,
    valorMeta: 2.0,
    recomendacao: "Implementar automação de alerta imediato para movimentações de relevância alta. Reduzir SLA para 48h.",
  },
  {
    categoria: "Taxa de atraso em tarefas",
    descricao: "18% das tarefas são concluídas após o prazo (meta: 8%)",
    impacto: "Alto",
    metrica: "% de tarefas atrasadas",
    valorAtual: 18,
    valorMeta: 8,
    recomendacao: "Revisar capacidade da equipe. Considerar contratação de 1 estagiário. Implementar alertas D-3 e D-1.",
  },
  {
    categoria: "Documentos pendentes de análise IA",
    descricao: "6 documentos aguardando análise IA há mais de 7 dias",
    impacto: "Médio",
    metrica: "Documentos pendentes >7 dias",
    valorAtual: 6,
    valorMeta: 0,
    recomendacao: "Processar lote de documentos pendentes. Ativar automação de análise imediata no upload.",
  },
  {
    categoria: "Clientes inativos >60 dias",
    descricao: "4 clientes sem atualização há mais de 60 dias",
    impacto: "Médio",
    metrica: "Clientes inativos",
    valorAtual: 4,
    valorMeta: 1,
    recomendacao: "Enviar newsletter personalizada + proposta de reunião de acompanhamento. Risco de churn.",
  },
  {
    categoria: "Inadimplência de honorários",
    descricao: "12% dos honorários em atraso (meta: 5%)",
    impacto: "Alto",
    metrica: "% inadimplência",
    valorAtual: 12,
    valorMeta: 5,
    recomendacao: "Implementar lembretes automáticos D-7, D-1 e D+3. Considerar boletos com PIX para reduzir fricção.",
  },
];

export const analisesPreditivas: AnalisePreditiva[] = [
  {
    processoId: "p-003",
    processoNumeroCnj: "1009876-54.2023.8.26.0100",
    clienteNome: "TechNova Soluções S/A",
    probabilidadeMovimentacao30d: 88,
    riscoPerdaPrazo: 35,
    diasSemMovimentacao: 6,
    recomendacao: "Prazo fatal em 16 dias. Iniciar contrarrazões imediatamente. Alta probabilidade de movimentação do tribunal (intimação).",
  },
  {
    processoId: "p-002",
    processoNumeroCnj: "0045678-12.2024.5.01.0007",
    clienteNome: "Ricardo Almeida Souza",
    probabilidadeMovimentacao30d: 72,
    riscoPerdaPrazo: 18,
    diasSemMovimentacao: 14,
    recomendacao: "Audiência inicial em 4 dias. Probabilidade moderada de acordo (60%). Preparar proposta antecipada.",
  },
  {
    processoId: "p-001",
    processoNumeroCnj: "0012345-67.2023.5.02.0001",
    clienteNome: "Construtora Horizonte Ltda",
    probabilidadeMovimentacao30d: 45,
    riscoPerdaPrazo: 25,
    diasSemMovimentacao: 4,
    recomendacao: "Sentença parcial publicada. Avaliar recurso ordinário em 8 dias. Custo-benefício favorável (~40% probabilidade).",
  },
  {
    processoId: "p-004",
    processoNumeroCnj: "0023456-78.2025.4.03.6100",
    clienteNome: "Construtora Horizonte Ltda",
    probabilidadeMovimentacao30d: 32,
    riscoPerdaPrazo: 5,
    diasSemMovimentacao: 8,
    recomendacao: "Baixo risco. Alta probabilidade de êxito (85%). Aguardar resposta da autoridade coatora. Cobrar honorários de sucesso.",
  },
  {
    processoId: "p-005",
    processoNumeroCnj: "0078901-23.2024.8.26.0010",
    clienteNome: "Helena Ferreira Martins",
    probabilidadeMovimentacao30d: 28,
    riscoPerdaPrazo: 12,
    diasSemMovimentacao: 22,
    recomendacao: "Processo parado há 22 dias. Considerar petição de juntada de prova ou requerimento de urgência. Atualizar cliente.",
  },
];

// Mais eventos de agenda para popular o calendário
export const eventosAgendaCompletos: EventoAgenda[] = [
  ...eventosAgenda,
  {
    id: "e-006",
    titulo: "Prazo — Recurso Ordinário Bezerra",
    data: "2026-08-01",
    hora: "23:59",
    tipo: "Prazo",
    processoId: "p-001",
    clienteNome: "Construtora Horizonte Ltda",
  },
  {
    id: "e-007",
    titulo: "Reunião equipe — Revisão semanal",
    data: "2026-08-04",
    hora: "09:00",
    tipo: "Reunião",
  },
  {
    id: "e-008",
    titulo: "Diligência — Cartório de Protestos",
    data: "2026-08-08",
    hora: "11:00",
    tipo: "Diligência",
  },
  {
    id: "e-009",
    titulo: "Vencimento — Honorários Horizonte",
    data: "2026-08-05",
    hora: "12:00",
    tipo: "Prazo",
    clienteNome: "Construtora Horizonte Ltda",
  },
  {
    id: "e-010",
    titulo: "Reunião estratégia — TechNova",
    data: "2026-08-09",
    hora: "15:00",
    tipo: "Reunião",
    processoId: "p-003",
    clienteNome: "TechNova Soluções S/A",
  },
  {
    id: "e-011",
    titulo: "Vencimento — Honorários Helena",
    data: "2026-08-10",
    hora: "12:00",
    tipo: "Prazo",
    clienteNome: "Helena Ferreira Martins",
  },
  {
    id: "e-012",
    titulo: "Diligência — Perícia contábil",
    data: "2026-08-14",
    hora: "10:00",
    tipo: "Diligência",
    processoId: "p-001",
    clienteNome: "Construtora Horizonte Ltda",
  },
  {
    id: "e-013",
    titulo: "Reunião — Logística Expressa (prospect)",
    data: "2026-08-19",
    hora: "16:00",
    tipo: "Reunião",
    clienteNome: "Logística Expressa S/A",
  },
  {
    id: "e-014",
    titulo: "Vencimento — Honorários sucesso Ricardo",
    data: "2026-08-15",
    hora: "12:00",
    tipo: "Prazo",
    clienteNome: "Ricardo Almeida Souza",
  },
  {
    id: "e-015",
    titulo: "Prazo — Petição de juntada Helena",
    data: "2026-08-22",
    hora: "23:59",
    tipo: "Prazo",
    processoId: "p-005",
    clienteNome: "Helena Ferreira Martins",
  },
];

// Notificações extras para a Central
export const notificacoesExtras: Notificacao[] = [
  {
    id: "n-006",
    titulo: "Cliente Helena Martins sem contato há 21 dias",
    descricao: "Recomendamos enviar atualização por e-mail hoje.",
    tipo: "warning",
    lida: false,
    dataHora: "2026-07-26T07:00:00Z",
    link: "copiloto-proativo",
  },
  {
    id: "n-007",
    titulo: "Documento faltante — TechNova",
    descricao: "Contrato SLA, e-mails de notificação e faturas ainda não anexados.",
    tipo: "error",
    lida: false,
    dataHora: "2026-07-26T06:00:00Z",
    link: "processos",
  },
  {
    id: "n-008",
    titulo: "Aluguel do escritório em atraso",
    descricao: "Vencimento 31/07. Pagar imediatamente para evitar multas.",
    tipo: "error",
    lida: false,
    dataHora: "2026-07-26T05:00:00Z",
    link: "financeiro",
  },
  {
    id: "n-009",
    titulo: "Tendência jurisprudencial favorável — Tributário",
    descricao: "STF: 87% de decisões favoráveis em exclusão ICMS/PIS-COFINS (Tema 69).",
    tipo: "info",
    lida: false,
    dataHora: "2026-07-25T18:00:00Z",
    link: "jurisprudencia",
  },
  {
    id: "n-010",
    titulo: "Oportunidade de acordo — Ricardo Souza",
    descricao: "60% de probabilidade de acordo na faixa de R$ 24-34 mil.",
    tipo: "info",
    lida: false,
    dataHora: "2026-07-25T15:00:00Z",
    link: "copiloto-proativo",
  },
];
